#!/usr/bin/env sh
#scan
gym
zip -r Bitbucket.app.zip Bitbucket.app
notes=$(git log -1 --pretty=%B)
commit=$(git rev-parse HEAD)
repository=$(git config --get remote.origin.url)
output=$(curl -s -X POST -H "X-HockeyAppToken: $HOCKEYAPP_TOKEN" -F "ipa=@Bitbucket.app.zip" -F "dsym=@Bitbucket.app.dSYM.zip" -F "notes=$notes" -F "notes_type=0" -F "notify=0" -F "status=2" -F "strategy=replace" -F "mandatory=0" -F "commit_sha=$commit" -F "repository_url=$repository"  https://rink.hockeyapp.net/api/2/apps/$HOCKEYAPP_APPID/app_versions/)
echo $output
result=$(echo $output | jq 'if .status == "error" then .message else "" end')
if [ ${#result} -ne 2 ]; then
  echo $result
  exit 1
fi
